apiVersion: v1
kind: Service
metadata:
  name: switchyard-colocated
  namespace: dynamo
spec:
  selector:
    nvidia.com/dynamo-graph-deployment-name: efficient
    nvidia.com/dynamo-component: VllmDecodeWorker
  ports:
  - name: http
    port: 4000
    targetPort: 4000
