apiVersion: v1
kind: Service
metadata:
  name: switchyard-production-rr
  namespace: dynamo
spec:
  selector:
    app: switchyard-production-rr
  ports:
  - name: router
    port: 4000
    targetPort: 4000
